### ISSUE TITLE
conda build does not allow for installation into large directory structures

### ISSUE THREAD

**Issue by danielsf** [mjuric/conda-lsst#63]
see

https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/210

Basically: somewhere inside of the conda build, a limited number of characters are allotted for the root directory into which the conda packages are installed.  Shared machines at large computing centers a la NERSC run afoul of this limit by forcing everyone's home directory to live at the end of a very long directory tree.  This causes the installation of the conda package to fail.

**Comment by mjuric** [comment]
The particular symptom mentioned in https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/210  is an upstream issue with Continuum's build of `swig`, and the fact their binary prefixes are currently limited to 80 characters (see [here for the code](https://github.com/conda/conda-build/blob/c43325f9a1191d1dbaa8a0e3ba1ecbc1b3644b35/conda_build/config.py#L60) and [here for the docs](http://conda.pydata.org/docs/building/meta-yaml.html#relocatable)).

@heather999, could you open an issue at https://github.com/conda/conda-build/issues asking them for a change (you could even change [the offending line](https://github.com/conda/conda-build/blob/c43325f9a1191d1dbaa8a0e3ba1ecbc1b3644b35/conda_build/config.py#L60) to, say, 128 instead of 80 characters, and directly open a PR)? It was already [discussed here](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/fgDBJ2YwETI) so it may be uncontroversial.

That said, this did make me think about our recipes and the fact we have `detect_binary_files_with_prefix` set to False. I should probably flip it to `True`, as we're now shipping much more than just Python code!

**Comment by heather999** [comment]
Thanks, @mjuric, with all that background information, I could hardly refuse trying a PR :)
https://github.com/heather999/conda-build/tree/heather999-increase-placehold-length-to-128

**Comment by heather999** [comment]
Thanks, @mjuric, with all that background information, I could hardly refuse trying a PR :)
https://github.com/conda/conda-build/pull/877

**Comment by mjuric** [comment]
Closing as this is an upstream issue with conda.
